"use client";

import * as React from "react";
import { Section, CodeFile } from "@/data/sections-registry";
import { CodebaseSimple } from "@/components/kibo-ui/codebase-simple";
import { getCodeFilesForSection } from "@/data/section-code-files";

interface SectionCodeViewerProps {
  section: Section;
  className?: string;
}

/**
 * Wrapper component that displays code files for a section using the CodebaseSimple component.
 * Automatically uses code files generated from actual component sources.
 * Falls back to manual files or default example if auto-generated files are not available.
 */
export function SectionCodeViewer({
  section,
  className,
}: SectionCodeViewerProps) {
  // Get files with priority: auto-generated > manual > default example
  const files = React.useMemo((): CodeFile[] => {
    // 1. Try to get auto-generated files from actual component sources
    const autoGeneratedFiles = getCodeFilesForSection(section.id);
    if (autoGeneratedFiles && autoGeneratedFiles.length > 0) {
      return autoGeneratedFiles;
    }

    // 2. Use manually provided files from the section
    if (section.files && section.files.length > 0) {
      return section.files;
    }

    // 3. Fallback: Generate a default usage example
    return [
      {
        id: `${section.id}-usage`,
        name: `${section.id}.tsx`,
        language: "tsx",
        code: `// Install this component with the command:
// ${section.installCommand}

import { ${section.name.replace(/\s+/g, "")} } from "@/components/sections/${section.category}/${section.id}";

export default function Page() {
  return (
    <div>
      <${section.name.replace(/\s+/g, "")} />
    </div>
  );
}`,
        path: `app/${section.id}.tsx`,
      },
    ];
  }, [section]);

  return (
    <CodebaseSimple
      files={files}
      defaultSelectedFile={files[0]?.id}
      className={className}
    />
  );
}
